(АКА-12) Сделал удаление локации из таблицы и её обновление после редактирования таргета
FocusStartSpb/Map pull request #103
Opened 2020-01-13 08:55 UTC by belannik

+ Парочка изменений:

- Теперь удаление ячеек реализовано только правым свайпом

- Переопределять размеры у дефолтной табличной вьюшки удаления это больно, поэтому пришлось изменить подход к ячейкам. Теперь каждая ячейка - новая секция. Нужно для того, что бы определить расстояние между ними

Всё остальное должно быть понятно из коммитов :)

2020-01-13 10:49 UTC, FlightyNEO requested changes

2020-01-13 10:49 UTC, FlightyNEO commented on Map/Business layer/Models/SmartTargetCollection.swift
> +	func replace(on new: SmartTarget)
Функция put() заменит элемент, если элемент с таким же uid уже есть

2020-01-13 10:49 UTC, FlightyNEO commented on Map/Business layer/SceneBuilder.swift
> +		presenter.attachViewController(detailTargetViewController: viewController)
Это через инициализатор презента можно передавить

2020-01-13 10:49 UTC, FlightyNEO commented on Map/Scenes/Smart target list scene/Cell/SmartTargetTableViewCell.swift
> +		return dateString
Для этого я экстеншен создал, посмотри пожалуйста в файл Formatter+Extension.swift

2020-01-13 10:49 UTC, FlightyNEO commented on Map/Scenes/Smart target list scene/Cell/SmartTargetTableViewCell.swift
> +		self.timeOfCreationLabel.text = dateFormat(dateOfCreation: smartTarget?.dateOfCreated)
Выше написал про экстеншен к Forrmatter
Formatter.medium.string(from: smartTarget?.dateOfCreated ?? Date())

2020-01-13 10:49 UTC, FlightyNEO commented on Map/Scenes/Smart target list scene/Detail target scene/DetailTargetPresenter.swift
> +	private weak var viewController: DetailTargetViewController?
Зачем weak?

2020-01-13 10:49 UTC, FlightyNEO commented on Map/Scenes/Smart target list scene/Detail target scene/DetailTargetPresenter.swift
> +	private weak var viewController: DetailTargetViewController?
Тут weak не нужен и VC через инициализатор можно передавать

2020-01-13 10:49 UTC, FlightyNEO commented on Map/Scenes/Smart target list scene/Detail target scene/DetailTargetPresenter.swift
> +		return dateString
Опять же в экстеншен можно вынести

2020-01-13 10:49 UTC, FlightyNEO commented on Map/Scenes/Smart target list scene/Detail target scene/DetailTargetViewController.swift
> +		didSet {
минор. Может декомпозировать этот код на 2 функции?

2020-01-13 10:49 UTC, FlightyNEO commented on Map/Scenes/Smart target list scene/Detail target scene/DetailTargetViewController.swift
> +	private func mapViewNotEditable() {
NotEditable == Uneditable ?

2020-01-13 10:50 UTC, belannik commented on Map/Business layer/Models/SmartTargetCollection.swift
> +	func replace(on new: SmartTarget)
Уже сделано

2020-01-13 10:54 UTC, belannik commented on Map/Scenes/Smart target list scene/Detail target scene/DetailTargetViewController.swift
> +		didSet {
Можно было бы и в экшенах у кнопок проставлять значения.
Я специально для этого вывел переменную, что бы было нагляднее и все делалось в одном месте. Мне показалось что так более наглядно

2020-01-13 15:26 UTC, K-Khud submitted a review, later dismissed

2020-01-14 13:22 UTC, FlightyNEO approved these changes

2020-01-14 14:55 UTC, K-Khud approved these changes

2020-01-14 17:00 UTC, merged