(AKA-6) Карта с получением геолокации пользователя
FocusStartSpb/Map pull request #14
Opened 2019-12-17 19:57 UTC by K-Khud

2019-12-17 20:12 UTC, belannik submitted a review, later dismissed

2019-12-17 20:12 UTC, belannik commented on Map/Scenes/Map scene/MapVCExtension.swift
> +	private func zoomToLatestLocation(with coordinate: CLLocationCoordinate2D) {
Это же приватная функция класса, а не протокола?

2019-12-17 20:43 UTC, FlightyNEO commented
Почему у тебя названия комитов AKA-7. Это ж другая задача совсем?

2019-12-17 20:50 UTC, K-Khud commented
> Почему у тебя названия комитов AKA-7. Это ж другая задача совсем?

просчиталась... теперь не знаю, как название кометов исправлять. Название ветки исправила.

2019-12-17 20:51 UTC, K-Khud commented on Map/Scenes/Map scene/MapVCExtension.swift
> +	private func zoomToLatestLocation(with coordinate: CLLocationCoordinate2D) {
Исправлено.

2019-12-17 21:50 UTC, FlightyNEO requested changes

2019-12-17 21:50 UTC, FlightyNEO commented on .gitignore
> +*.xcuserstate
Это что такое? 🤔

2019-12-17 21:50 UTC, FlightyNEO commented on Map/Scenes/Map scene/MapVCExtension.swift
> +//  MapVCExtension.swift
MapVCExtension???

Файл должен называться MapViewController+CLLocationManagerDelegate

2019-12-17 21:50 UTC, FlightyNEO commented on Map/Scenes/Map scene/MapVCExtension.swift
> +import Foundation
Можно не писать если есть import MapKit

2019-12-17 21:50 UTC, FlightyNEO commented on Map/Scenes/Map scene/MapVCExtension.swift
> +		if self.currentCoordinate == nil {
self можно не писать

2019-12-17 21:50 UTC, FlightyNEO commented on Map/Scenes/Map scene/MapVCExtension.swift
> +		self.currentCoordinate = latestLocation.coordinate
и тут тоже

2019-12-17 21:50 UTC, FlightyNEO commented on Map/Scenes/Map scene/MapViewController.swift
>  import UIKit
Тоже можно не писать import UIKit

2019-12-17 21:50 UTC, FlightyNEO commented on Map/Scenes/Map scene/MapVCExtension.swift
> +	private func zoomToLatestLocation(with coordinate: CLLocationCoordinate2D) {
Думаю лучше назвать goToLatestLocation(with:) или showLatestLocation(with:)
zoom подразумевает увеличение/уменьшение.

2019-12-17 21:50 UTC, FlightyNEO commented on Map/Scenes/Map scene/MapViewController.swift
> +	let longtitudalMeters: Double = 5000
все private должно быть

2019-12-17 21:50 UTC, FlightyNEO commented on Map/Scenes/Map scene/MapViewController.swift
> +	let longtitudalMeters: Double = 5000
можно создать структуру 
`CoordinateMeters { latitude, longtitude: Double }`

И тип можно явно не указывать, если написать так:
`let longtitudalMeters = 5000.0`
А еще красивее так ) :
`let longtitudalMeters = 5_000.0`

2019-12-17 21:50 UTC, FlightyNEO commented on Map/Scenes/Map scene/MapViewController.swift
> +		}
Лучше через switch
<img width="679" alt="Снимок экрана 2019-12-18 в 00 18 16" src="https://user-images.githubusercontent.com/18489711/71035170-f7a02780-212b-11ea-922d-8b2edfe9fde1.png">

2019-12-17 21:50 UTC, FlightyNEO commented on Map/Scenes/Map scene/MapViewController.swift
> +	func beginLocationUpdates(locationManager: CLLocationManager) {
private func

2019-12-17 21:50 UTC, FlightyNEO commented on Map/Scenes/Map scene/MapViewController.swift
> +		mapView.topAnchor.constraint(equalTo: view.topAnchor, constant: 0).isActive = true
А почему тут не view.safeAreaLayoutGuide?

2019-12-17 21:50 UTC, FlightyNEO commented on Map/Scenes/Map scene/MapViewController.swift
> +	private func configureLocationServices() {
почему во множественном числе Services?

2019-12-17 21:50 UTC, FlightyNEO commented on Map/Scenes/Map scene/MapViewController.swift
> +	let longtitudalMeters: Double = 5000
опечатка longitudinal

2019-12-18 10:15 UTC, MisnikovRoman commented
> Почему у тебя названия комитов AKA-7. Это ж другая задача совсем?

Надо исправлять

2019-12-18 10:28 UTC, MisnikovRoman requested changes

2019-12-18 10:28 UTC, MisnikovRoman commented on Map/Scenes/Map scene/MapVCExtension.swift
> +extension MapViewController: CLLocationManagerDelegate
⚠️ Работу с геолокацией лучше выносить в отдельный сервис, ну и плюс если у вас архитектура MVP, работа с геолокацией должна происходить в Presenter-e

2019-12-18 12:32 UTC, K-Khud commented on .gitignore
> +*.xcuserstate
попытки вылечить gitignore

2019-12-18 14:56 UTC, FlightyNEO commented on Map/Scenes/Map scene/MapVCExtension.swift
> +extension MapViewController: CLLocationManagerDelegate
Да точно!

2019-12-18 16:41 UTC, K-Khud commented on Map/Scenes/Map scene/MapVCExtension.swift
> +//  MapVCExtension.swift
исправлено

2019-12-18 16:42 UTC, K-Khud commented on Map/Scenes/Map scene/MapVCExtension.swift
> +import Foundation
исправлено

2019-12-18 16:43 UTC, K-Khud commented on Map/Scenes/Map scene/MapVCExtension.swift
> +		if self.currentCoordinate == nil {
ok

2019-12-18 16:43 UTC, K-Khud commented on Map/Scenes/Map scene/MapVCExtension.swift
> +		self.currentCoordinate = latestLocation.coordinate
ok

2019-12-19 07:50 UTC, MisnikovRoman requested changes

2019-12-19 07:50 UTC, MisnikovRoman commented on Map/Scenes/Map scene/MapInteractor.swift
>  	private var worker: DataWorker
А что за абстрактный `DataWorker`?

2019-12-19 07:50 UTC, MisnikovRoman commented on Map/Scenes/Map scene/MapModels.swift
> +			let coordinate: CLLocationCoordinate2D
А почему нельзя в презентер сразу передавать координаты (`CLLocationCoordinate2D`)? Зачем оборачивать в сущность с одним параметром?

2019-12-19 07:50 UTC, MisnikovRoman commented on Map/Scenes/Map scene/MapModels.swift
> +			let coordinate: CLLocationCoordinate2D
И зачем отдельная вью-модель, которая дублирует Response?

2019-12-19 07:50 UTC, MisnikovRoman commented on Map/Scenes/Map scene/MapViewController.swift
> +	let locationManager = CLLocationManager()
Все еще locationManager в VC? Ему тут не место

2019-12-19 07:50 UTC, MisnikovRoman commented on Map/Scenes/Map scene/MapViewController.swift
> +	let longtitudalMeters: Double = 5000
> 5_000.0

о_О "красивее"?

2019-12-19 15:20 UTC, FlightyNEO commented on Map/Scenes/Map scene/MapViewController.swift
> +	let longtitudalMeters: Double = 5000
и все приватное должно быть

2019-12-19 15:20 UTC, FlightyNEO commented on Map/Scenes/Map scene/MapViewController.swift
> +	//var currentCoordinate: CLLocationCoordinate2D?
удалить закомиченную строку

2019-12-19 15:20 UTC, FlightyNEO commented on Map/Scenes/Map scene/MapViewController.swift
> +	}
можно удалить

2019-12-19 15:20 UTC, FlightyNEO commented on Map/Scenes/Map scene/MapInteractor.swift
>  	private var worker: DataWorker
Почему абстрактный? Это worker работающий с данными на диске.

2019-12-19 15:20 UTC, FlightyNEO commented on Map/Scenes/Map scene/MapModels.swift
> +			let coordinate: CLLocationCoordinate2D
Архитектура Clean Swift построена на передаче данных внутри цикла view-interactor-presenter с помощью структур. 
Вью к интерактору - запрос
Интерактор к презентеру - ответ
Презентер к вью - вьюМодел

2019-12-19 15:20 UTC, FlightyNEO commented on Map/Scenes/Map scene/MapModels.swift
> +			let coordinate: CLLocationCoordinate2D
[Clean Swift](https://clean-swift.com/)

2019-12-19 15:20 UTC, FlightyNEO commented on Map/Scenes/Map scene/MapViewController.swift
> +	let longtitudalMeters: Double = 5000
> о_О "красивее"?

Мне нравится, более наглядно, нули считать не надо )

2019-12-19 16:24 UTC, MisnikovRoman commented on Map/Scenes/Map scene/MapInteractor.swift
>  	private var worker: DataWorker
Data - универсальный тип, почти Any, Worker'ом - можно назвать любой сущность, которая что-то делает. Вот и получается максимально абстрактно и непонятно

2019-12-19 16:26 UTC, MisnikovRoman commented on Map/Scenes/Map scene/MapModels.swift
> +			let coordinate: CLLocationCoordinate2D
да, я и забыл, что у вас Clean Swift

2019-12-19 18:00 UTC, K-Khud commented on Map/Scenes/Map scene/MapViewController.swift
> +	//var currentCoordinate: CLLocationCoordinate2D?
ok

2019-12-19 18:00 UTC, K-Khud commented on Map/Scenes/Map scene/MapViewController.swift
> +	}
ok

2019-12-19 18:21 UTC, K-Khud commented on Map/Scenes/Map scene/MapViewController.swift
> +		}
сделала через if, но поменяла так, что во всех случаях, кроме .authorizedAlways и .authorizedWhenInUse, будет запрос авторизации (.notDetermoned,  .denied)

2019-12-19 18:21 UTC, K-Khud commented on Map/Scenes/Map scene/MapViewController.swift
> +	func beginLocationUpdates(locationManager: CLLocationManager) {
вынесла его в протокол и переименовала

2019-12-19 18:21 UTC, K-Khud commented on Map/Scenes/Map scene/MapViewController.swift
> +		mapView.topAnchor.constraint(equalTo: view.topAnchor, constant: 0).isActive = true
чтобы карта заполняла всю верхнюю часть и игнорировала topAnchor у safeArea.

2019-12-19 18:21 UTC, K-Khud commented on Map/Scenes/Map scene/MapViewController.swift
> +	private func configureLocationServices() {
done

2019-12-19 18:21 UTC, K-Khud commented on Map/Scenes/Map scene/MapViewController.swift
> +	let longtitudalMeters: Double = 5000
Сделала 5_000.0

2019-12-20 15:12 UTC, K-Khud commented on Map/Scenes/Map scene/MapInteractor.swift
>  	private var worker: DataWorker
исправили в другой задаче

2019-12-22 07:48 UTC, K-Khud commented on Map/Scenes/Map scene/MapViewController.swift
> +	let locationManager = CLLocationManager()
исправлено

2019-12-22 15:20 UTC, K-Khud commented on Map/Scenes/Map scene/MapViewController.swift
> +		}
в общем-то вернулась к твоему варианту со switch

2019-12-22 15:42 UTC, MisnikovRoman submitted a review, later dismissed

2019-12-22 15:55 UTC, FlightyNEO submitted a review, later dismissed

2019-12-22 15:55 UTC, FlightyNEO commented on Map/Scenes/Map scene/MapInteractor.swift
> +	}
Минор. В .notDetermined и в default происходит одно и то же, можно case .notDetermined убрать

2019-12-22 15:55 UTC, FlightyNEO commented on Map/Scenes/Map scene/MapInteractor.swift
> +																			   userCoordinate: latestCoordinate))
лишний enter

2019-12-22 17:04 UTC, belannik approved these changes

2019-12-22 17:07 UTC, FlightyNEO approved these changes

2019-12-22 17:14 UTC, merged