(AKA-40) Добавила alert при нажатии на remove
FocusStartSpb/Map pull request #78
Opened 2019-12-30 13:12 UTC by K-Khud

2019-12-30 14:05 UTC, FlightyNEO commented
В целом я бы вынес создание UIAlertAction в константы, а потом уже добавлял их к алерту.
`let okAction = UIAlertAction(.............. `
`alert.addAction(okAction)`

2019-12-30 14:10 UTC, FlightyNEO commented
И я не понял логики 

1. после нажатия на "Remove" в меню, всплывает алерт 

2. - после нажатия на "Remove" - пин удаляется
    - после нажатия на "Save pin" - пин сохраняется

А может не "Save pin" сделать а "Cancel", дав возможность пользователю дальше редактировать, и если ему нужно будет сохранить, то кнопка "Save" есть в меню.

2019-12-30 14:11 UTC, FlightyNEO requested changes

2019-12-30 14:11 UTC, FlightyNEO commented on Map/Scenes/Map scene/MapViewController.swift
> +									  message: "You can always add a new pin again.", preferredStyle: UIAlertController.Style.alert)
Можно просто `.alert`

2019-12-30 14:11 UTC, FlightyNEO commented on Map/Scenes/Map scene/MapViewController.swift
> +		alert.addAction(UIAlertAction(title: "Save pin", style: UIAlertAction.Style.default, handler: { _ in
То же самое `.default`

2019-12-30 14:11 UTC, FlightyNEO commented on Map/Scenes/Map scene/MapViewController.swift
> +									  style: UIAlertAction.Style.destructive,
То же `.destructive`

2019-12-30 14:11 UTC, FlightyNEO commented on Map/Scenes/Map scene/MapViewController.swift
> +									  handler: {(_: UIAlertAction) in
handler: { [weak self] _ in

2020-01-11 09:31 UTC, FlightyNEO commented
Еще надо бы учитывать настройку пользователя во вкладке настроек что выставлена у пользователя
<img width="461" alt="Снимок экрана 2020-01-11 в 12 24 14" src="https://user-images.githubusercontent.com/18489711/72202156-5fb50580-346d-11ea-9a53-e3cd611a03df.png">

`settingsWorker.forceRemovePin`
Если `true`, то показывать Алерт, если `false`, то не показывать

2020-01-12 18:37 UTC, K-Khud commented
Вынесла создание alert в файл Alerts.
Логика следующая: при первом нажатии на Remove показывается предупреждение о том, что повторное действие удалит пин, что и происходит.
Алерт не показывается, если либо для этого пина пользователь уже нажимал на remove и видел алерт, либо в настройках отключен показ алертов.

2020-01-12 18:40 UTC, K-Khud commented on Map/Scenes/Map scene/MapViewController.swift
> +									  handler: {(_: UIAlertAction) in
поменяла.

2020-01-12 18:41 UTC, K-Khud commented on Map/Scenes/Map scene/MapViewController.swift
> +									  style: UIAlertAction.Style.destructive,
убрала деструктивные действия

2020-01-12 18:42 UTC, K-Khud commented on Map/Scenes/Map scene/MapViewController.swift
> +									  message: "You can always add a new pin again.", preferredStyle: UIAlertController.Style.alert)
сделала

2020-01-12 18:42 UTC, K-Khud commented on Map/Scenes/Map scene/MapViewController.swift
> +		alert.addAction(UIAlertAction(title: "Save pin", style: UIAlertAction.Style.default, handler: { _ in
сделала

2020-01-12 19:32 UTC, belannik submitted a review, later dismissed

2020-01-13 04:41 UTC, FlightyNEO commented on Map/Business layer/Alerts.swift
> +import Foundation
Можно не писать

2020-01-13 05:33 UTC, FlightyNEO requested changes
Не работает 3 случая:

- пользователь начал создавать пин, после перешел в настройки, изменил "предупреждение", вернулся обратно. Это можно посчитать за фитчу, а не баг ))) видео скину

- удаление редактируемого пина, после нажатия на "удалить", а после "ок", надо бы вернуть "actionSheet" обратно, а то меню пропадает, и все приехали )) Видео скину

- Не работает при перетягивании пина, а не карты: надо свойство `removePinWithoutAlertRestricted` в `true` установить  в методе `mapView(_ mapView: MKMapView, annotationView view: MKAnnotationView, didChange newState: MKAnnotationView.DragState, fromOldState oldState: MKAnnotationView.DragState)` в кейсе `case (.ending, .none)`. видео скину

Так же надо свойство `removePinWithoutAlertRestricted ` в `false` устанавливать в методе `setupDefaultSettings()`

2020-01-13 05:33 UTC, FlightyNEO commented on Map/Business layer/UserPreferences.swift
> +	@SettingWrapper(key: Key[.forceRemovePin], defaultValue: true)
👍

2020-01-13 05:33 UTC, FlightyNEO commented on Map/Scenes/Map scene/MapViewController.swift
> +		interactor.getRemovePinAlertSettings(.init())
Не понял зачем это здесь, чтобы мы настройку получали при каждом удалении / сохранении / добавлении пина?

Давай это пропишем в `viewWillAppear`.
Тогда будет работать случай, при котором пользователь начал создавать пин, потом переключился на вкладку настроек, поменял настройку, вернулся обратно, ........

Видео "бага" отправлю в телеграм

2020-01-13 05:33 UTC, FlightyNEO commented on Map/Scenes/Map scene/MapViewController.swift
> +		interactor.getRemovePinAlertSettings(.init())
Выше уже написал давай в `viewWillAppear` вынесем это вызов

2020-01-13 05:33 UTC, FlightyNEO commented on Map/Scenes/Map scene/MapViewController.swift
> +		removePinWithoutAlertRestricted = true
Я бы вынес эту строку в метод `mapView(_ mapView: MKMapView, regionDidChangeAnimated animated: Bool)` перед строкой `animatePinViewHidden(false)`

Вот почему
- название функции говорит о добавлении поинтера, но не об изменении настройки, не относящейся к поинтеру
- Этот метод вызывается в методе `mapViewDidChangeVisibleRegion(_ mapView: MKMapView)`, который вызывается при перемещении карты многократно, а нам по сути надо это свойство в `true` сделать, после перемещения пина, поэтому логичнее это сделать либо в момент начала перемещения карты, либо в момент окончания перемещения карты

2020-01-13 05:33 UTC, FlightyNEO commented on Map/Scenes/Map scene/MapViewController.swift
> +		Alerts.showDeletePinAlert(on: self)
Отступ пропустила

2020-01-13 05:33 UTC, FlightyNEO commented on Map/Business layer/Alerts.swift
> +		alert.addAction(UIAlertAction(title: "OK", style: .default, handler: nil))
`handler: nil` можно не писать

2020-01-13 13:36 UTC, K-Khud commented on Map/Business layer/Alerts.swift
> +import Foundation
done

2020-01-13 13:40 UTC, K-Khud commented on Map/Scenes/Map scene/MapViewController.swift
> +		removePinWithoutAlertRestricted = true
ok

2020-01-13 13:40 UTC, K-Khud commented on Map/Scenes/Map scene/MapViewController.swift
> +		interactor.getRemovePinAlertSettings(.init())
ok

2020-01-13 13:40 UTC, K-Khud commented on Map/Scenes/Map scene/MapViewController.swift
> +		interactor.getRemovePinAlertSettings(.init())
ok

2020-01-13 13:42 UTC, K-Khud commented on Map/Scenes/Map scene/MapViewController.swift
> +		Alerts.showDeletePinAlert(on: self)
done )

2020-01-13 13:43 UTC, K-Khud commented on Map/Business layer/Alerts.swift
> +		alert.addAction(UIAlertAction(title: "OK", style: .default, handler: nil))
ok, спасибо

2020-01-13 17:55 UTC, FlightyNEO approved these changes

2020-01-13 17:56 UTC, belannik approved these changes

2020-01-13 17:56 UTC, merged