(АКА-42) Сцена редактирования smart target'ов
FocusStartSpb/Map pull request #92
Opened 2020-01-06 16:54 UTC by belannik

2020-01-06 23:06 UTC, FlightyNEO commented
Мои мысли. 

- Date of creation вместе с самой датой не отображать вовсе в detail, а только в ячейках

- Лэйблы title и address не отображать, только содержимое, Думаю юзер догадается что к чему, хотя в режиме редактирования title можно оставить 🤔

- То что в режиме редактирования табБар скрыт это хорошо я считаю

2020-01-06 23:55 UTC, FlightyNEO requested changes
Сцена Detail Сделана по MVP вроде. Ну ок, Тогда презентер тебе не нужен, он у тебя пустой. Точнее Интерактор в презентер переименовать надо.
Кое что не покрыто протоколами, исправь пожалуйста
И основное надо исправить передачу данных при роутинге, хотя бы из Таблицы в Детэйл сделать по клинСвифтовски. А роутиться из детей обратно пускай так и остается.

2020-01-06 23:55 UTC, FlightyNEO commented on Map/Scenes/Smart target list scene/Cell/SmartTargetTableViewCell.swift
> +			}
Минор. Что бы не проверять userInterfaceStyle, можно эти цвета в assets добавить и указать для них цвета для темной и светлой темы.

2020-01-06 23:55 UTC, FlightyNEO commented on Map/Scenes/Smart target list scene/Detail target scene/DetailTargetInteractor.swift
> +	}
передавать smartTarget в инициализаторе не по CleanSwift`овски. Его нужно передавать в роутере. В первом методе передаем через протокой DataStore данные. Во втором навигируемся к контролеру.
При чем названия методов должны начинаться так 
```
routeTo....... {
    passDataTo.......
    navigateTo.......
}
```

<img width="1157" alt="Снимок экрана 2020-01-07 в 02 19 51" src="https://user-images.githubusercontent.com/18489711/71856191-322a2e00-30f4-11ea-9bd3-174e04831430.png">

2020-01-06 23:55 UTC, FlightyNEO commented on Map/Scenes/Smart target list scene/Detail target scene/DetailTargetRouter.swift
> +	}
А это надо в инициализаторе устанавливать

2020-01-06 23:55 UTC, FlightyNEO commented on Map/Scenes/Smart target list scene/Detail target scene/DetailTargetViewController.swift
> +	private let interactor: DetailTargetInteractor
Должен быть протокол IDetailTargetInteractor

2020-01-06 23:55 UTC, FlightyNEO commented on Map/Scenes/Smart target list scene/Detail target scene/DetailTargetViewController.swift
> +	init(interactor: DetailTargetInteractor,
IDetailTargetInteractor

2020-01-06 23:55 UTC, FlightyNEO commented on Map/Scenes/Smart target list scene/Detail target scene/DetailTargetViewController.swift
> +		self.router.attachViewController(detailTargetViewController: self)
Уже писа выше, надо через инициализатор роутера в фабрике устанавливать это

2020-01-06 23:55 UTC, FlightyNEO commented on Map/Scenes/Smart target list scene/Detail target scene/DetailTargetViewController.swift
> +		self.view.addGestureRecognizer(UITapGestureRecognizer(target: self,
Я бы вынес в отдельную функцию `setup()`

2020-01-06 23:55 UTC, FlightyNEO commented on Map/Scenes/Smart target list scene/Detail target scene/DetailTargetViewController.swift
> +		topAnchor.priority = UILayoutPriority(999)
Могу ошибаться, но по-моему можно `.defaultHigh` использовать. Или какую-то другую константу.

2020-01-06 23:55 UTC, FlightyNEO commented on Map/Scenes/Smart target list scene/SmartTargetListRouter.swift
> +									 smartTarget: smartTarget)
Уже писал. smartTarget надо передавать через протокол SmartTargetListDataStore.

2020-01-06 23:55 UTC, FlightyNEO commented on Map/Scenes/Smart target list scene/Detail target scene/DetailTargetInteractor.swift
> +}
Как я вижу сцена Detail не по CleanSweeft сделана. Ок пусть так оно и остается.

2020-01-07 00:01 UTC, FlightyNEO commented
Я не проверял обновление таблицы после изменения смарт таргета. Надеюсь она не обновляется полностью, а обновляется только нужна ячейка.
Так же надеюсь что после перехода на карту, удаленные и отредактированные пины удалятся / обновятся на карте. Я вроде эти методы прописывал в таблице.

2020-01-07 02:15 UTC, FlightyNEO commented on Map/Scenes/Smart target list scene/Detail target scene/DetailTargetRouter.swift
> +	}
Точнее в фабрике `router.viewController = detailTargetViewController`

2020-01-07 04:47 UTC, FlightyNEO commented
> Мои мысли.
> 
> * Date of creation вместе с самой датой не отображать вовсе в detail, а только в ячейках
> * Лэйблы title и address не отображать, только содержимое, Думаю юзер догадается что к чему, хотя в режиме редактирования title можно оставить 🤔
> * То что в режиме просмотра табБар скрыт это ок, но в режиме редактирования давай тоже будем прятать табБар, чтобы не получилось такого сценария (в таблице начали редактировать пин, перешли на MapVC удалили или отредактировали этот самый пин, перешли обратно к редактированию в Detail, и непонятно что делать, т. к. этот пин уже удалили (отредактировали)). Да тот же сценарий справедлив и в обратном направлении, когда мы начали редактировать на Мапе и перешли в таблицу, удалили там этот пин. Думаю надо скрывать табБар и на Мапе при редактировании. При создании не обязательно, так как пин еще не будет создан.

Можно выставить в `SmartTargetListViewController` свойство `tabBarController?.hidesBottomBarWhenPushed`, что бы при переходе к Detail, tabBar прятался.

В MapVC уже сделал чтобы tabBar прятался при редактировании

2020-01-07 04:53 UTC, FlightyNEO commented
> Пока не особо придумал, как можно сообщить юзеру о возможности редактирования текствью и ограничился только рамкой и небольшим изменением бэкграунда, сорян :( Если есть идеи - буду оч благодарен

Идей особо нету, может сделать текст с подчеркиванием. Ну я бы предложил задать title для viewController`а с текстом _Edit_

2020-01-07 12:40 UTC, belannik commented on Map/Scenes/Smart target list scene/Cell/SmartTargetTableViewCell.swift
> +			}
Можно, просто мне показалось что если сделать так, то в последующем изменения UI будут более наглядными

2020-01-09 08:41 UTC, FlightyNEO submitted a review, later dismissed

2020-01-09 20:36 UTC, K-Khud submitted a review, later dismissed

2020-01-10 06:05 UTC, FlightyNEO approved these changes

2020-01-10 09:29 UTC, K-Khud approved these changes

2020-01-10 09:30 UTC, merged